In [5]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [6]:
df = pd.read_csv("Data.csv")

In [7]:
df.shape

(66, 5)

In [8]:
df.head()

,Favorite Color,Favorite Music Genre,Favorite Beverage,Favorite Soft Drink,Gender
0,Cool,Rock,Vodka,7UP/Sprite,F
1,Neutral,Hip hop,Vodka,Coca Cola/Pepsi,F
2,Warm,Rock,Wine,Coca Cola/Pepsi,F
3,Warm,Folk/Traditional,Whiskey,Fanta,F
4,Cool,Rock,Vodka,Coca Cola/Pepsi,F

In [9]:
df.isnull().sum()

Favorite Color          0
Favorite Music Genre    0
Favorite Beverage       0
Favorite Soft Drink     0
Gender                  0
dtype: int64

In [10]:
df['Favorite Color'].unique()

array(['Cool', 'Neutral', 'Warm'], dtype=object)

In [11]:
df['Favorite Music Genre'].unique()

array(['Rock', 'Hip hop', 'Folk/Traditional', 'Jazz/Blues', 'Pop',
       'Electronic', 'R&B and soul'], dtype=object)

In [12]:
df['Favorite Beverage'].unique()

array(['Vodka', 'Wine', 'Whiskey', "Doesn't drink", 'Beer', 'Other'],
      dtype=object)

In [13]:
df['Favorite Soft Drink'].unique()

array(['7UP/Sprite', 'Coca Cola/Pepsi', 'Fanta', 'Other'], dtype=object)

In [181]:
df['Favorite Beverage'].nunique()

6

In [182]:
df['Favorite Color'].nunique()

3

In [183]:
df['Favorite Music Genre'].nunique()

7

In [184]:
df['Favorite Soft Drink'].nunique()

4

In [185]:
df = pd.get_dummies(data =  df, dtype = int)

In [186]:
df.head()

,Favorite Color_Cool,Favorite Color_Neutral,Favorite Color_Warm,Favorite Music Genre_Electronic,Favorite Music Genre_Folk/Traditional,Favorite Music Genre_Hip hop,Favorite Music Genre_Jazz/Blues,Favorite Music Genre_Pop,Favorite Music Genre_R&B and soul,Favorite Music Genre_Rock,...,Favorite Beverage_Other,Favorite Beverage_Vodka,Favorite Beverage_Whiskey,Favorite Beverage_Wine,Favorite Soft Drink_7UP/Sprite,Favorite Soft Drink_Coca Cola/Pepsi,Favorite Soft Drink_Fanta,Favorite Soft Drink_Other,Gender_F,Gender_M
0,1,0,0,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,0,1,0
1,0,1,0,0,0,1,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
2,0,0,1,0,0,0,0,0,0,1,...,0,0,0,1,0,1,0,0,1,0
3,0,0,1,0,1,0,0,0,0,0,...,0,0,1,0,0,0,1,0,1,0
4,1,0,0,0,0,0,0,0,0,1,...,0,1,0,0,0,1,0,0,1,0

In [187]:
df_columns = df.columns

In [188]:
df_columns

Index(['Favorite Color_Cool', 'Favorite Color_Neutral', 'Favorite Color_Warm',
       'Favorite Music Genre_Electronic',
       'Favorite Music Genre_Folk/Traditional', 'Favorite Music Genre_Hip hop',
       'Favorite Music Genre_Jazz/Blues', 'Favorite Music Genre_Pop',
       'Favorite Music Genre_R&B and soul', 'Favorite Music Genre_Rock',
       'Favorite Beverage_Beer', 'Favorite Beverage_Doesn't drink',
       'Favorite Beverage_Other', 'Favorite Beverage_Vodka',
       'Favorite Beverage_Whiskey', 'Favorite Beverage_Wine',
       'Favorite Soft Drink_7UP/Sprite', 'Favorite Soft Drink_Coca Cola/Pepsi',
       'Favorite Soft Drink_Fanta', 'Favorite Soft Drink_Other', 'Gender_F',
       'Gender_M'],
      dtype='object')

In [189]:
x = df.drop("Gender_M", axis = 1)
y = df['Gender_M']

In [190]:
from sklearn.model_selection import train_test_split

In [191]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.4, random_state = 66)

In [192]:
from sklearn.linear_model import LogisticRegression

In [193]:
lg = LogisticRegression()

In [194]:
lg.fit(x, y)

LogisticRegression()

In [195]:
y_pred = lg.predict(x_test)

In [196]:
from sklearn.metrics import accuracy_score

In [197]:
accuracy_score(y_test, y_pred)

1.0

In [198]:
from sklearn.tree import DecisionTreeClassifier

In [199]:
dt = DecisionTreeClassifier(max_depth=50)

In [200]:
dt.fit(x, y)

DecisionTreeClassifier(max_depth=50)

In [201]:
y_pred_dt = dt.predict(x_test)

In [202]:
accuracy_score(y_test, y_pred_dt)

1.0

In [203]:
df = pd.read_csv("Data.csv")

In [204]:
df.head()

,Favorite Color,Favorite Music Genre,Favorite Beverage,Favorite Soft Drink,Gender
0,Cool,Rock,Vodka,7UP/Sprite,F
1,Neutral,Hip hop,Vodka,Coca Cola/Pepsi,F
2,Warm,Rock,Wine,Coca Cola/Pepsi,F
3,Warm,Folk/Traditional,Whiskey,Fanta,F
4,Cool,Rock,Vodka,Coca Cola/Pepsi,F

In [205]:
y = df['Gender']
x = df.drop("Gender", axis = 1)

In [206]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [207]:
ohe = OneHotEncoder()

In [208]:
ohe.fit(x)

OneHotEncoder()

In [209]:
ohe.transform(x)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 264 stored elements and shape (66, 20)>

In [210]:
trf1 = ColumnTransformer(transformers = [
    ("encoding", OneHotEncoder(sparse_output=False),[0,1,2,3])
], remainder="passthrough")

In [211]:
transformed_data = trf1.fit_transform(x)

In [212]:
len(df_columns)

22

In [213]:
df_columns = list(df_columns)

In [214]:
# df_columns.pop()
# df_columns.pop()

'Gender_F'

In [215]:
len(df_columns)

20

In [216]:
df_columns

['Favorite Color_Cool',
 'Favorite Color_Neutral',
 'Favorite Color_Warm',
 'Favorite Music Genre_Electronic',
 'Favorite Music Genre_Folk/Traditional',
 'Favorite Music Genre_Hip hop',
 'Favorite Music Genre_Jazz/Blues',
 'Favorite Music Genre_Pop',
 'Favorite Music Genre_R&B and soul',
 'Favorite Music Genre_Rock',
 'Favorite Beverage_Beer',
 "Favorite Beverage_Doesn't drink",
 'Favorite Beverage_Other',
 'Favorite Beverage_Vodka',
 'Favorite Beverage_Whiskey',
 'Favorite Beverage_Wine',
 'Favorite Soft Drink_7UP/Sprite',
 'Favorite Soft Drink_Coca Cola/Pepsi',
 'Favorite Soft Drink_Fanta',
 'Favorite Soft Drink_Other']

In [217]:
transformed_df = pd.DataFrame(
    transformed_data,
    columns = df_columns
)

In [218]:
transformed_df

,Favorite Color_Cool,Favorite Color_Neutral,Favorite Color_Warm,Favorite Music Genre_Electronic,Favorite Music Genre_Folk/Traditional,Favorite Music Genre_Hip hop,Favorite Music Genre_Jazz/Blues,Favorite Music Genre_Pop,Favorite Music Genre_R&B and soul,Favorite Music Genre_Rock,Favorite Beverage_Beer,Favorite Beverage_Doesn't drink,Favorite Beverage_Other,Favorite Beverage_Vodka,Favorite Beverage_Whiskey,Favorite Beverage_Wine,Favorite Soft Drink_7UP/Sprite,Favorite Soft Drink_Coca Cola/Pepsi,Favorite Soft Drink_Fanta,Favorite Soft Drink_Other
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
62,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
63,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
64,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
65,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [219]:
y = pd.get_dummies(y, drop_first=True, dtype = int)
y

    M
0   0
1   0
2   0
3   0
4   0
.. ..
61  1
62  1
63  1
64  1
65  1

[66 rows x 1 columns]

In [220]:
y = y.values.ravel()

In [221]:
from sklearn.model_selection import train_test_split

In [222]:
x_train, x_test, y_train, y_test = train_test_split(transformed_df, y, test_size=0.45, random_state=66)

In [223]:
from sklearn.ensemble import RandomForestClassifier

In [224]:
rf = RandomForestClassifier()

In [225]:
rf.fit(transformed_df, y)

RandomForestClassifier()

In [226]:
y_pred_rf = rf.predict(x_test)

In [227]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [228]:
y_test

array([1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1])

In [229]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1])

In [ ]:
accuracy_score(y_test, y_pred_rf)

In [231]:
confusion_matrix(y_test, y_pred_rf)

array([[10,  2],
       [ 0, 18]], dtype=int64)

In [232]:
from sklearn.pipeline import Pipeline

In [233]:
pipe = Pipeline(steps = [
    ("encoding values", trf1), 
    ("Random Forest Model", RandomForestClassifier())
])

In [234]:
p = pipe.fit(x,y)

In [235]:
y_pred_pipe = p.predict(x)

In [236]:
accuracy_score(y, y_pred_pipe)

0.9545454545454546

In [237]:
import pickle

In [238]:
with open("gender_classification_thinking.pkl", "wb") as file:
    pickle.dump(pipe, file)

In [239]:
with open("gender_classification_thinking.pkl", "rb") as file:
    model_pipe = pickle.load(file)

In [240]:
y_pred_pickle = model_pipe.predict(x)

In [241]:
accuracy_score(y, y_pred_pickle)

0.9545454545454546

In [242]:
df.head()

,Favorite Color,Favorite Music Genre,Favorite Beverage,Favorite Soft Drink,Gender
0,Cool,Rock,Vodka,7UP/Sprite,F
1,Neutral,Hip hop,Vodka,Coca Cola/Pepsi,F
2,Warm,Rock,Wine,Coca Cola/Pepsi,F
3,Warm,Folk/Traditional,Whiskey,Fanta,F
4,Cool,Rock,Vodka,Coca Cola/Pepsi,F

In [243]:
# Cool	Rock	Vodka	7UP/Sprite

In [244]:
test_data = [['Cool', 'Rock', 'Vodka', '7UP/Sprite']]

In [245]:
model_pipe.predict(test_data)

c:\Users\manit\anaconda3\envs\ml\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([0])

In [246]:
# 0 -> Female
# 1 -> Male